@EVStation_basedRendtalSystem.Services.StationAPI_HostAddress = http://localhost:5135

GET {{EVStation_basedRendtalSystem.Services.StationAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
